1704/school/config/routes.rb
Rails.application.routes.draw do
  resources :events do
  collection do
    get 'all'
  end
end
  resources :people
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

1704/school/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

1704/school/app/models/event.rb
class Event < ApplicationRecord
    belongs_to :person,  :foreign_key => "people_id"
end

1704/school/app/models/person.rb
class Person < ApplicationRecord
    has_many :event
end

1704/school/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

1704/school/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end
  def all
    strl = DateTime.now.to_i.to_s
    #strl.to_i.to_s
    strm = (DateTime.now + 5).to_i.to_s
    #strm.to_i.to_s
    #str2 = "strftime('%s', date_of_e )> strftime('%s', 'now') and strftime('%s', date_of_e) < "+strm+""
    str2 = "CAST(strftime('%s', date_of_e)  AS  integer) > CAST(strftime('%s', 'now')  AS  integer) and CAST(strftime('%s', date_of_e)  AS  integer) < "+strm+""
       # @events = Event.all
    @events = Event.where(str2)
    #format.json { render :json => @question }
    #render :json => @question 
  end
  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date_of_e, :description, :people_id)
    end
end

1704/school/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:relatoship, :last_name, :first_name, :second_name, :sex)
    end
end

1704/school/app/helpers/application_helper.rb
module ApplicationHelper
end

1704/school/app/helpers/events_helper.rb
module EventsHelper
end

1704/school/app/helpers/people_helper.rb
module PeopleHelper
end

1704/school/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_of_e %>
    <%= form.date_select :date_of_e %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
  <%= form.label :person %>
  <%= form.collection_select :people_id, Person.all, :id , :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

1704/school/app/views/events/all.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Date of e</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.date_of_e %></td>
        <td><%= event.description %></td>
        <td><%= event.people_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

1704/school/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

1704/school/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Date of e</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.date_of_e %></td>
        <td><%= event.description %></td>
        <td><%= event.people_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

1704/school/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

1704/school/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of e:</strong>
  <%= @event.date_of_e %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

1704/school/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

1704/school/app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :relatoship %>
    <%= form.text_field :relatoship %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :second_name %>
    <%= form.text_field :second_name %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.check_box :sex %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

1704/school/app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

1704/school/app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Relatoship</th>
      <th>Last name</th>
      <th>First name</th>
      <th>Second name</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.relatoship %></td>
        <td><%= person.last_name %></td>
        <td><%= person.first_name %></td>
        <td><%= person.second_name %></td>
        <td><%= person.sex %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

1704/school/app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

1704/school/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Relatoship:</strong>
  <%= @person.relatoship %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @person.second_name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @person.sex %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>