lab0603/config/routes.rb
Rails.application.routes.draw do
 
  resources :groups
  resources :students do
    collection do
      get 'search'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

lab0603/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab0603/app/models/group.rb
class Group < ApplicationRecord
    has_many :students
end

lab0603/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :group

  def self.search(params)
    result = Student.includes(:group)
    if params['ln'].present?
      result = result.where(ln: params['ln'])
    end
    if params['name'].present?
      result = result.where(groups: {name: params['name']})
    end
    result.all
  end
end

lab0603/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

lab0603/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

lab0603/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def search
    #render html: '<html><body>Some body text</body></html>'.html_safe ## Add html_safe
    params['search'] ||= {} 

    if params.has_key?('search')
      @students = Student.search(params['search'])
    else
      @students = []
    end
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:ln, :fn, :sn, :group_id)
    end
end

lab0603/app/helpers/application_helper.rb
module ApplicationHelper
end

lab0603/app/helpers/groups_helper.rb
module GroupsHelper
end

lab0603/app/helpers/students_helper.rb
module StudentsHelper
end

lab0603/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab0603</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lab0603/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ln %>
    <%= form.text_field :ln %>
  </div>

  <div class="field">
    <%= form.label :fn %>
    <%= form.text_field :fn %>
  </div>

  <div class="field">
    <%= form.label :sn %>
    <%= form.text_field :sn %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lab0603/app/views/students/_resultse.html.erb
<% @students.each do |s| %>
    <%= s.ln %>
    <br/>
    <%= s.fn %>
    <br/>
    <%= s.sn %>
    <br/>
    <%= s.group.name %>
    <br/>
    <% end %>

lab0603/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

lab0603/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Ln</th>
      <th>Fn</th>
      <th>Sn</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.ln %></td>
        <td><%= student.fn %></td>
        <td><%= student.sn %></td>
        <td><%= student.group.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

lab0603/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

lab0603/app/views/students/search.html.erb
<%= form_tag search_students_path(), method: :get do %>
    <%= text_field_tag 'search[ln]', params['search']['ln'] %>
    <%= text_field_tag 'search[name]', params['search']['name'] %>
    <%= submit_tag 'Искать' %>
    <% end %>
    <%= render 'resultse' %>

lab0603/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ln:</strong>
  <%= @student.ln %>
</p>

<p>
  <strong>Fn:</strong>
  <%= @student.fn %>
</p>

<p>
  <strong>Sn:</strong>
  <%= @student.sn %>
</p>

<p>
  <strong>Group:</strong>
  <%= @student.group.id %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>